package hibernate.pojo;
// Generated 2 Apr, 2015 12:00:56 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TblPlant generated by hbm2java
 */
public class TblPlant  implements java.io.Serializable {


     private BigDecimal IPlantId;
     private String TPlantName;
     private String TPlantOwner;

    public TblPlant() {
    }

	
    public TblPlant(BigDecimal IPlantId) {
        this.IPlantId = IPlantId;
    }
    public TblPlant(BigDecimal IPlantId, String TPlantName, String TPlantOwner) {
       this.IPlantId = IPlantId;
       this.TPlantName = TPlantName;
       this.TPlantOwner = TPlantOwner;
    }
   
    public BigDecimal getIPlantId() {
        return this.IPlantId;
    }
    
    public void setIPlantId(BigDecimal IPlantId) {
        this.IPlantId = IPlantId;
    }
    public String getTPlantName() {
        return this.TPlantName;
    }
    
    public void setTPlantName(String TPlantName) {
        this.TPlantName = TPlantName;
    }
    public String getTPlantOwner() {
        return this.TPlantOwner;
    }
    
    public void setTPlantOwner(String TPlantOwner) {
        this.TPlantOwner = TPlantOwner;
    }




}


