package hibernate.pojo;
// Generated Apr 7, 2015 9:20:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;

/**
 * TblProcess generated by hbm2java
 */
public class TblProcess  implements java.io.Serializable {

@Column(columnDefinition = "serial")
     private BigDecimal IProcessId;
     private TblPlant tblPlant;
     private String TProcessType;
     private Set tblMappings = new HashSet(0);

    public TblProcess() {
    }

	
    public TblProcess(TblPlant tblPlant) {
        this.tblPlant = tblPlant;
    }
    public TblProcess(TblPlant tblPlant, String TProcessType, Set tblMappings) {
       this.tblPlant = tblPlant;
       this.TProcessType = TProcessType;
       this.tblMappings = tblMappings;
    }
   
    public BigDecimal getIProcessId() {
        return this.IProcessId;
    }
    
    public void setIProcessId(BigDecimal IProcessId) {
        this.IProcessId = IProcessId;
    }
    public TblPlant getTblPlant() {
        return this.tblPlant;
    }
    
    public void setTblPlant(TblPlant tblPlant) {
        this.tblPlant = tblPlant;
    }
    public String getTProcessType() {
        return this.TProcessType;
    }
    
    public void setTProcessType(String TProcessType) {
        this.TProcessType = TProcessType;
    }
    public Set getTblMappings() {
        return this.tblMappings;
    }
    
    public void setTblMappings(Set tblMappings) {
        this.tblMappings = tblMappings;
    }




}


