package hibernate.pojo;
// Generated Apr 2, 2015 12:31:44 PM by Hibernate Tools 4.3.1



/**
 * TblUsers generated by hbm2java
 */
public class TblUsers  implements java.io.Serializable {


     private String SUsername;
     private TblPlant tblPlant;
     private String SPassword;
     private String SPasswordMd5;

    public TblUsers() {
    }

	
    public TblUsers(String SUsername, TblPlant tblPlant, String SPasswordMd5) {
        this.SUsername = SUsername;
        this.tblPlant = tblPlant;
        this.SPasswordMd5 = SPasswordMd5;
    }
    public TblUsers(String SUsername, TblPlant tblPlant, String SPassword, String SPasswordMd5) {
       this.SUsername = SUsername;
       this.tblPlant = tblPlant;
       this.SPassword = SPassword;
       this.SPasswordMd5 = SPasswordMd5;
    }
   
    public String getSUsername() {
        return this.SUsername;
    }
    
    public void setSUsername(String SUsername) {
        this.SUsername = SUsername;
    }
    public TblPlant getTblPlant() {
        return this.tblPlant;
    }
    
    public void setTblPlant(TblPlant tblPlant) {
        this.tblPlant = tblPlant;
    }
    public String getSPassword() {
        return this.SPassword;
    }
    
    public void setSPassword(String SPassword) {
        this.SPassword = SPassword;
    }
    public String getSPasswordMd5() {
        return this.SPasswordMd5;
    }
    
    public void setSPasswordMd5(String SPasswordMd5) {
        this.SPasswordMd5 = SPasswordMd5;
    }




}


